"""Phase 6: offboarding reports, member status, is_public on artifacts/insights.

Revision ID: 006_offboarding_public_kb
Revises: 005_knowledge_verification
Create Date: 2026-04-09
"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

revision: str = "006_offboarding_public_kb"
down_revision: str | None = "005_knowledge_verification"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ── Members: lifecycle status ─────────────────────────────────────────────
    op.add_column(
        "members",
        sa.Column("status", sa.String(20), nullable=True, server_default="active"),
    )
    op.create_index("ix_members_status", "members", ["status"])

    # ── Artifacts: public knowledge base ─────────────────────────────────────
    op.add_column(
        "artifacts",
        sa.Column("is_public", sa.Boolean(), nullable=True, server_default="false"),
    )
    op.create_index("ix_artifacts_is_public", "artifacts", ["is_public"])

    # ── Insights: public knowledge base ──────────────────────────────────────
    op.add_column(
        "insights",
        sa.Column("is_public", sa.Boolean(), nullable=True, server_default="false"),
    )
    op.create_index("ix_insights_is_public", "insights", ["is_public"])

    # ── Offboarding reports ───────────────────────────────────────────────────
    op.create_table(
        "offboarding_reports",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column(
            "member_id",
            sa.String(),
            sa.ForeignKey("members.id", ondelete="CASCADE"),
            nullable=False,
            index=True,
        ),
        sa.Column(
            "created_by",
            sa.String(),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        # Expertise areas only this member contributes to
        sa.Column("unique_expertise", sa.JSON(), server_default="[]"),
        # Artifact IDs where this member is the sole contributor
        sa.Column("sole_contributor_artifact_ids", sa.JSON(), server_default="[]"),
        # List of {topic, recommended_member_id, recommended_member_name} objects
        sa.Column("transfer_recommendations", sa.JSON(), server_default="[]"),
        # Overall risk level: "low" | "medium" | "high" | "critical"
        sa.Column("risk_level", sa.String(20), nullable=True),
        # Free-text summary (generated by LLM if available, else rule-based)
        sa.Column("summary", sa.Text(), nullable=True),
        # Raw computed data for re-rendering
        sa.Column("report_data", sa.JSON(), server_default="{}"),
    )


def downgrade() -> None:
    op.drop_table("offboarding_reports")

    op.drop_index("ix_insights_is_public", table_name="insights")
    op.drop_column("insights", "is_public")

    op.drop_index("ix_artifacts_is_public", table_name="artifacts")
    op.drop_column("artifacts", "is_public")

    op.drop_index("ix_members_status", table_name="members")
    op.drop_column("members", "status")
